HiTalent/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('HiTalentDashboard.urls'),name='app'),
    path('',views.home_page,name='home'),
    path('aboutus/',views.about_us,name='about')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HiTalentDashboard/urls.py
from django.urls import path
from HiTalentDashboard import views

app_name = 'app'

urlpatterns = [
    path('dashboard/', views.list_of_candidates, name='dashboard')
]

HiTalentDashboard/models.py
from django.db import models

# Create your models here.

class candidate(models.Model):

    fresher = 'fresher'
    one = 1
    two = 2
    three = 3
    four = 4
    five = 5
    fiveplus = '5+'

    Experirnce_choices = [
        ('fresher',fresher),
        ('1',one),
        ('2',two),
        ('3',three),
        ('4',four),
        ('5',five),
        ('5+',fiveplus)
    ]

    # candidate_id = models.IntegerField(unique=True, primary_key=True, blank=False)
    candidate_name = models.CharField(max_length=256, blank=False)
    candidate_experience = models.CharField(max_length=7, choices=Experirnce_choices, default=fresher)  ## testby changeing max_length
    candidate_tech_stack = models.TextField(default='')
    candidate_placed = models.BooleanField()

    def __str__(self,*args,**kwargs):
        return self.candidate_name

HiTalent/views.py
from django.shortcuts import render

# Create your views here.

def home_page(request):
    return render(request, 'homepage.html')

def about_us(request):
    return render(request, 'about.html')

HiTalentDashboard/views.py
from django.shortcuts import render
from .models import candidate

# Create your views here.

def list_of_candidates(request):
    all_candidates = candidate.objects.all()
    # number_of_candidates = len(all_candidates)
    
    placed_candidates = candidate.objects.filter(candidate_placed=True)
    available_candidates = candidate.objects.filter(candidate_placed=False)

    # number_of_placed_candidates = len(placed_candidates)
    # number_of_available_candidates = len(available_candidates)

    context = {'all_candidates':all_candidates, 'available_candidates':available_candidates, 'placed_candidates':placed_candidates}
    return render(request, 'HiTalentDashboard/dashboard.html', context)

templates/HiTalentDashboard/dashboard.html
{% extends 'base.html' %}


{% block body %}

    <h2>Total of Candidates Avaiable: {{ all_candidates | length }} </h2>

    <h2>Candidates Placed: {{ placed_candidates | length }}</h2>

    <h2>No. of Talents Available: {{ available_candidates | length }}</h2>

{% endblock body %}

templates/about.html
{% extends 'base.html' %}


{% block body %}

    <h2>About Us</h2>
    <h3>Lorem ipsum dolor sit, amet consectetur adipisicing elit.
         Deleniti tenetur et, velit nihil eum praesentium expedita inventore unde asperiores fugiat reiciendis sequi commodi quod aliquid debitis sapiente molestiae at laboriosam.</h3>
    
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. 
        At atque odio porro consectetur aliquam quisquam modi, 
        tempore quae culpa cupiditate placeat quam consequuntur aut explicabo eligendi nulla illo molestias hic.</p>

{% endblock body %}
    

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hi-Talent</title>
</head>
<body>
    <center>
        <h1>Hi Talent</h1>
        <a href=" {% url 'home' %} ">HOME</a> 
        <br>
        <a href=" {% url 'app:dashboard' %} ">DASHBOARD</a>
        <br>
        <a href=" {% url 'about' %} ">ABOUT US</a>
        <br>


    
    {% block head %}
        
    {% endblock head %}
        
    
    {% block body %}
        
    {% endblock body %}
    </center>

</body>
</html>

templates/homepage.html
{% extends 'base.html' %}

{% block body %}

    <h2>Welcome to Hi-Talent Website</h2>

    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
         Saepe quaerat fuga vero ratione itaque maiores aperiam molestias eos voluptatem ad,
          dolor nemo error. Ipsum beatae ipsa repellendus laudantium,
           perferendis id.<p>

    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. 
        Dolorum quas incidunt sunt hic. Magni doloremque dicta excepturi porro, 
        ab doloribus quam, ipsam at tempore, explicabo eligendi provident dolores facilis a</p>

    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit.
         Corrupti perferendis optio similique quia molestias asperiores.
          Vero pariatur iure in ullam. Nemo voluptatum in sapiente at recusandae eligendi eius error soluta!</p>

{% endblock body %}